// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChVQQEf3e-zb5-1xfeVuLcIpEcHZEmT4s',
    appId: '1:1038539323507:web:f9edfe3502592ef0c31206',
    messagingSenderId: '1038539323507',
    projectId: 'recovery-app-2e538',
    authDomain: 'recovery-app-2e538.firebaseapp.com',
    storageBucket: 'recovery-app-2e538.appspot.com',
    measurementId: 'G-CBJP3KTEB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHua9rXMaPTW62OdD3MjKP3E1gD6cT9LM',
    appId: '1:1038539323507:android:0d33040cc8776965c31206',
    messagingSenderId: '1038539323507',
    projectId: 'recovery-app-2e538',
    storageBucket: 'recovery-app-2e538.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-tuIwRISrJylC6_GrzCt7kCnZmKsqvP4',
    appId: '1:1038539323507:ios:46e6d443aead441cc31206',
    messagingSenderId: '1038539323507',
    projectId: 'recovery-app-2e538',
    storageBucket: 'recovery-app-2e538.appspot.com',
    iosClientId: '1038539323507-khdsrp8spviq38o4j7gebbijl2vondop.apps.googleusercontent.com',
    iosBundleId: 'com.example.recoveryApp',
  );
}
